FROM mysql:latest as builder
RUN ["sed", "-i", "s/exec \"$@\"/echo \"not running $@\"/", "/usr/local/bin/docker-entrypoint.sh"]
ENV MYSQL_ROOT_PASSWORD=root
COPY setup.sql /docker-entrypoint-initdb.d/
RUN ["/usr/local/bin/docker-entrypoint.sh", "mysqld", "--datadir", "/initialized-db"]
FROM mysql:latest
COPY --from=builder /initialized-db /var/lib/mysql

FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8081
ADD /build/libs/Lelang-User-0.0.1-SNAPSHOT.jar Lelang-User-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Lelang-User-0.0.1-SNAPSHOT.jar"]