FROM mysql
ENV MYSQL_DATABASE lelangin_test
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/

FROM openjdk:8-jdk-alpine
VOLUME /tmp
EXPOSE 8081
ADD /build/libs/Lelang-User-0.0.1-SNAPSHOT.jar Lelang-User-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Lelang-User-0.0.1-SNAPSHOT.jar"]